---
title: "Haszn치laut칩.hu"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, comment = "", message = F, warning = F)
```

## Scrape k칩d futtat치sa

```{r results='hide'}
library(tidyverse)
library(httr)
req <- GET("https://api.github.com/repos/MarcellGranat/hasznaltauto/git/trees/main?recursive=1")
stop_for_status(req)
filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F) %>% 
  c(
    list.files("c:/rprojects/hasznaltauto/data/available_cars"),
    list.files("c:/rprojects/hasznaltauto/data/cars_data")
  )

date <- filelist %>% 
  keep(~ str_detect(., "2021|2020")) %>% 
  gsub(pattern = ".*202", replacement = "202") %>% 
  str_remove_all(".RDS") %>% 
  append(str(Sys.Date())) %>% 
  unique() %>% 
  enframe() %>% 
  transmute(date = as.Date(value), done = T)
```

```{r fig.width=9}
date$date %>% 
  {seq.Date(from = as.Date("2021-05-01"), to = max(.), by = 1)} %>% 
  enframe() %>% 
  transmute(date = as.Date(value)) %>% 
  left_join(date) %>% 
  mutate(
    m = lubridate::month(date, label = T),
    w = lubridate::isoweek(date),
    d = lubridate::wday(date, label = T, week_start = 1)
  ) %>% 
  ggplot() + 
  aes(d, w, fill = done) +
  geom_tile(color = "black", show.legend = FALSE) +
  scale_fill_manual(values = c("cyan4", "grey20"), na.value = "grey20") +
  scale_y_continuous(expand = c(0,0), trans = "reverse") +
  facet_wrap(~ m, scales = "free_y", nrow = 1, labeller = as_labeller(str_to_upper)) + 
  ggdark::dark_theme_grey() +
  theme(
    axis.text.y = element_blank(),
    axis.ticks = element_blank()
  ) +
  labs(x = NULL, y = NULL)
```

